---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: latest
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04

suites:
- name: default
  run_list:
  - recipe[aws-sdk_test]
